[profile.default]
remappings = [
  "@chainlink=lib/chainlink/contracts/",
  "forge-std/=lib/forge-std/src/",
  "foundry-devops/=lib/foundry-devops/",
]

fs_permissions = [
  { access = "read", path = "./broadcast" },
  { access = "read", path = "./reports" },
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = false
solc_version = "0.8.24"
